[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.32", features = ["serde-serialize"] }
rand = "0.8"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
